### PR TITLE
feat: increase vega export quality on mobile

### PR DESCRIPTION
**Pull request by andreiradoi**

### CODE REVIEW

**Comment by jlewallen** [comment]
I've added an isMobile function to utilities.ts we should start using.

**Comment by jlewallen** [comment]
I think it's especially important because we seem to be using different values all over the place, 500 all the way up to 1024. Not sure why that is.

**Review by jlewallen — CHANGES_REQUESTED** [review]
Let's use isMobile here.

**Comment by andreiradoi** [comment]
@jlewallen Done. I've been using different as they made more sense depending on the context. I.E. Some screens look decent between 768 and 1080 and don't need a special mobile design.

**Comment by jlewallen** [comment]
If we need to we can create multiple copies of isMobile that are named in a way that makes their specific function easier to understand. I just want to get away from copying and pasting that expression everywhere.

**Pull request merged**
