### PR TITLE
Fk 4382

### PR DESCRIPTION
**Pull request by andreiradoi**

### CODE REVIEW

**Review by jlewallen — CHANGES_REQUESTED** [review]
I believe Sara has updated the ticket for this.

**Comment by andreiradoi** [comment]
@jlewallen implemented Sara's suggestions.

**Comment by andreiradoi** [comment]
@jlewallen fixed another issue reported by Sadie. Please redeploy

**Comment by jlewallen** [comment]
What's the status with this?

**Comment by jlewallen** [comment]
There are merge conflicts with this and the station page, would be nice if those were cleared up otherwise I'll have to get a separate build up for them.

**Pull request closed without merging**
