### PR TITLE
Fk 4514

### PR DESCRIPTION
**Pull request by andreiradoi**

### CODE REVIEW

**Comment by jlewallen** [comment]
Looks to still be in progress in Jira.

**Comment by jlewallen** [comment]
Is this ready? Doesn't seem like it will build right now?

**Comment by andreiradoi** [comment]
Not ready. I've passed this task for BE work to Achil. Will update you here when everything is ready.

**Comment by andreiradoi** [comment]
You'll see that getProjectsForStation is not used here, but will be used for https://fieldkit.monday.com/boards/3445320824/pulses/3830386684 so please keep it.

**Pull request merged**
